esphome:
  name: esp32_test

  libraries:
    #- "M5Stack"
    - "Wire"
    - "SPI"
    - "FS"
    - "SPIFFS"
    - "SD"
    - "M5Unit-Sonic"
    #- "HTTPClient"
    #- "WiFiClient"
  
external_components:
    - source:
        type: local
        path: components 

      components: [sonic_i2c]

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "update"

ota:
  password: "update"

wifi:
  ssid: "Livebox-36B0"
  password: "4CHfRsdx9C9c8VdH2t"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Test Fallback Hotspot"
    password: "ezOUB4lHEavi"

# SONIC I2C sensor configuration
sensor:
 - platform: sonic_i2c
   name: Distance Sensor
   unit_of_measurement: mm
   sda_pin: 25
   scl_pin: 23
   update_interval: 5s


# Switch Connected to ESP32 LED a GPIO2
switch:
  - platform: gpio
    name: "build_in_led"
    pin: 2

web_server:
  port: 80 




    